1: # Plot gains for full sky-model solutions
  command: "kal-plot gains"
  options:
    plot: [
      ["gains/true_gains.npy", "True Jones", "black", "-"],
      ["gains/cubical/tint_1/half-1-cubical.npy", "Cubical-1", "yellowgreen", "-"],
      ["gains/cubical/tint_12/full-12-cubical.npy", "Cubical-12", "red", "-"],
      ["gains/cubical/tint_120/full-120-cubical.npy", "Cubical-120", "purple", "-"]
    ]
    ref_ant: 0
    show: "0, 1, 2, 3"
    axis: "TIME"
    complex_axis: "REAL"
    title: "Gains magnitude plot over TIME (REAL)\n(FULL SKY-MODEL) - Multiple t-int"
    out_file: "plots/cubical/cubical_full_gp_plot.png"
    display: True

2: # Plot gains for half sky-model solutions
  command: "kal-plot gains"
  options:
    plot: [
      ["gains/true_gains.npy", "True Jones", "black", "-"],
      ["gains/cubical/tint_1/half-1-cubical.npy", "Cubical-1", "yellowgreen", "-"],
      ["gains/cubical/tint_12/half-12-cubical.npy", "Cubical-12", "red", "-"],
      ["gains/cubical/tint_120/half-120-cubical.npy", "Cubical-120", "purple", "-"]
    ]
    ref_ant: 0
    show: "0, 1, 2, 3"
    axis: "TIME"
    complex_axis: "REAL"
    title: "Gains magnitude plot over TIME (REAL)\n(HALF SKY-MODEL) - Multiple t-int"
    out_file: "plots/cubical/cubical_half_gp_plot.png"
    display: True