# Usage: With a skymodel and true input gains, create direction-independent
# model visibilities and measured visibilities (with added noise). Noise set
# drawn from ~ CN(0, 2) or 1 Jy per axis for the array 'KAT-7'.

# Dimensions:
#   n_time = 2 * 3600/10 = 720
#   n_ant = 7
#   n_chan = 1
#   n_dir = 1
#   n_corr = 4

1: # Data for KAT-7 on 1 src sky-model OR 70% modelled flux of 2 src sky-model
  command: "kal-create data"
  arguments:
    ms: "ms/kat7.ms"
    sky_model: "skymodels/kat7/model-src-1.txt"
    gains: "gains/true/kat7/kat7-src-1-gains.npy"
  options:
    std: 1.4142135623730951
    phase_convention: "CASA"
    die: True
    utime: 30
    ncpu: 20
    mname: "SRC1_MODEL"
    dname: "SRC1_DATA"

2: # Data for KAT-7 on 2 src sky-model @ 100% modelled flux
  command: "kal-create data"
  arguments:
    ms: "ms/kat7.ms"
    sky_model: "skymodels/kat7/model-src-2.txt"
    gains: "gains/true/kat7/kat7-src-2-gains.npy"
  options:
    std: 1.4142135623730951
    phase_convention: "CASA"
    die: True
    utime: 30
    ncpu: 20
    mname: "SRC2_MODEL"
    dname: "SRC2_DATA"