# Usage: Simulate direction-independent gains drawing from a gaussian process
# and applying to a square exponential function with a given time-scale, for
# the antenna array 'KAT-7'

# Dimensions:
#   n_time = 2 * 3600/10 = 720
#   n_ant = 7
#   n_chan = 1
#   n_dir = 1
#   n_corr = 4

# Correlations on diagonals-only

1: # Gains for KAT-7 on 1 src sky-model
  command: "kal-create gains"
  arguments:  
    ms: "ms/kat7.ms"
    sky_model: "skymodels/kat7/model-src-1.txt"
  options:
    type: "normal"
    std: 0.2                     
    diffs: [0.05, 0.05, 0.5]
    die: True
    out_file: "gains/true/kat7/kat7-src-1-gains.npy"

2: # Gains for KAT-7 on 2 src sky-model
  command: "kal-create gains"
  arguments:  
    ms: "ms/kat7.ms"
    sky_model: "skymodels/kat7/model-src-2.txt"
  options:
    type: "normal"
    std: 0.2                     
    diffs: [0.05, 0.05, 0.5]
    die: True
    out_file: "gains/true/kat7/kat7-src-2-gains.npy"